sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t brunokarpo/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true brunokarpo/docker-react npm run test

