sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t brunokarpo/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true brunokarpo/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "sa-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-sa-east-1-891872512359"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
